AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DynamoDBTableGlobalName:
    Type: 'String'

  DynamoDBTableJobsName:
    Type: 'String'

Resources:
  DynamoDBTableGlobal:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBTableGlobalName
      AttributeDefinitions:
        - AttributeName: 'name'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'name'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  DynamoDBTableJobs:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref DynamoDBTableJobsName
      AttributeDefinitions:
        - AttributeName: 'table_name'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'table_name'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1